### ISSUE TITLE
64 Bit Integer Buffers Not Supported in Python

### ISSUE THREAD

**Issue by jwfromm** [halide/Halide#2560]
I need to build a pipeline using 64 bit integers. I can do this fine from C++, but seem to be unable to construct a Buffer in python. For example:

```
B = Buffer(Int(64), 64, 64)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-43-5c4ed268a3fd> in <module>()
----> 1 B = Buffer(Int(64), 64, 64)

ValueError: BufferFactory::create_buffer_impl received type not handled
```

Is there a reason for this limitation? Are there any recommendations for working around it?

Thanks

**Comment by zvookin** [comment]
Hopefully it was just an oversight or some compatibility issue that no longer exists. I made the obvious changes in the above referenced PR. If you are building from source, please feel free to test my fix. Would do so myself but I am a bit pressed for time and I'm not yet well versed in the Python side of things.

**Comment by jwfromm** [comment]
This does seem to fix it, thanks!

**Comment by zvookin** [comment]
Hopefully fixed by https://github.com/halide/Halide/pull/2561, which I just merged.

**Comment by GuillaumeLeclerc** [comment]
I still have the problem and just built from source:

```
hl.Buffer(np.arange(0, 10).astype('uint64'))
```

fails with the same error.

**Comment by steven-johnson** [comment]
@GuillaumeLeclerc Can you provide a more complete example? (The Python bindings have been completely rewritten since this issue was last updated)

**Comment by GuillaumeLeclerc** [comment]
Sure,

Just add:

import halide as hl
import numpy as no

And that reproduces it.

Thank you for your support
