### ISSUE TITLE
If you store_at without a compute_at, the error message isn't very good:

### ISSUE THREAD

**Issue by abadams** [halide/Halide#7920]
```
#include "Halide.h"
#include <iostream>
using namespace Halide;

int main() {
    Func f, g;
    Var x;
    f(x) = x;
    g(x) = f(x);
    f.store_root();
    g.compile_jit();
    return 0;
}
```
produces:
```
Func "f" is computed at the following invalid location:
  f.compute_inline();
Legal locations for this function are:
  f.compute_root();
  f.compute_at(g, Var::outermost());
  f.compute_at(g, x);
"f" is used in the following places:
 for g.s0.x:
  g uses f
```
It should just say more directly that you can't do a store_at without a compute_at

**Comment by vksnk** [comment]
I've fixed it together with hoist_storage in #7915 .

**Comment by abadams** [comment]
In that branch it's better, but still not ideal:
```
Error:
Functions that are compute_inline() must also have store_at and hoist_storage set to inlined, but Func "f0" is store_at() "loop_level(.__root)" and hoist_storage() "loop_level(.__root)"
```

There's no store_at_inline, so it's a bit confusing. Also our printing of the loop level isn't very friendly. 

I think the ideal error message would be something like:

```
Error:
Func "f0" is scheduled store_root(), but is inlined. Funcs that use store_at or store_root must also call compute_at or compute_root.
```

and then something similar if hoist_storage is set without a compute_at. I'll leave this issue open for now to tweak the wording, but we shouldn't delay the hoist_storage PR on it.
